// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClipboardSetText(arg1) {
  return window['go']['main']['AppService']['ClipboardSetText'](arg1);
}

export function ComputeSavePath(arg1, arg2) {
  return window['go']['main']['AppService']['ComputeSavePath'](arg1, arg2);
}

export function GetDefaultPaths() {
  return window['go']['main']['AppService']['GetDefaultPaths']();
}

export function GetWxapkgItem(arg1) {
  return window['go']['main']['AppService']['GetWxapkgItem'](arg1);
}

export function Github() {
  return window['go']['main']['AppService']['Github']();
}

export function OpenDirectoryDialog(arg1, arg2) {
  return window['go']['main']['AppService']['OpenDirectoryDialog'](arg1, arg2);
}

export function OpenFileDialog(arg1, arg2, arg3) {
  return window['go']['main']['AppService']['OpenFileDialog'](arg1, arg2, arg3);
}

export function OpenPath(arg1) {
  return window['go']['main']['AppService']['OpenPath'](arg1);
}

export function OpenUrl(arg1) {
  return window['go']['main']['AppService']['OpenUrl'](arg1);
}

export function ScanWxapkgItem(arg1, arg2) {
  return window['go']['main']['AppService']['ScanWxapkgItem'](arg1, arg2);
}

export function UnpackWxapkgItem(arg1, arg2) {
  return window['go']['main']['AppService']['UnpackWxapkgItem'](arg1, arg2);
}

export function Version() {
  return window['go']['main']['AppService']['Version']();
}
