// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wechat} from '../models';
import {main} from '../models';

export function ClipboardSetText(arg1:string):Promise<void>;

export function ComputeSavePath(arg1:string,arg2:string):Promise<string>;

export function GetDefaultPaths():Promise<wechat.PathScanResult>;

export function GetWxapkgItem(arg1:string):Promise<wechat.WxapkgItem>;

export function Github():Promise<string>;

export function OpenDirectoryDialog(arg1:string,arg2:string):Promise<string>;

export function OpenFileDialog(arg1:string,arg2:string,arg3:Array<main.FileFilter>):Promise<string>;

export function OpenPath(arg1:string):Promise<void>;

export function OpenUrl(arg1:string):Promise<void>;

export function ScanWxapkgItem(arg1:string,arg2:boolean):Promise<Array<wechat.WxapkgItem>>;

export function UnpackWxapkgItem(arg1:wechat.WxapkgItem,arg2:wechat.UnpackOptions):Promise<void>;

export function Version():Promise<string>;
